### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by mikegfisher** [mikegfisher/Sample#1]
# Login
As a user, I want to be able to log in and out of the app. 

### Design
- [x] [InVision Project](https://support.invisionapp.com/hc/en-us/articles/206318755-Introduction-to-Workflow)

### Develop
- [x] mikegfisher/unknown-stag#9 Log in
- [x] mikegfisher/unknown-stag#33 Log out

### Tests
- [x] mikegfisher/test-unknown-stag#3 `.feature` Login behavior (Gherkin)
- [x] mikegfisher/test-unknown-stag#3 `.js` Login step definitions 

### Showing off
- [x] Doesn't need to even be a linked thing
